name: Build & Deploy to Cloud Run
'on':
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud build
        run: | # enable build layer caching with Kaniko
          gcloud config set builds/use_kaniko True
          gcloud config set builds/kaniko_cache_ttl 6

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag ${{ secrets.IMAGE_TAG }} \
              --gcs-log-dir gs://travellabel_cloudbuild_logs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} \
              --image ${{ secrets.IMAGE_TAG }} \
              --region asia-southeast2
